version: '3'
services:
  authentication-service:
    build: authentication-service/.
    ports:
      - 8091:8040
    depends_on:
      - payroll-mysql
  payroll-mysql:
    image: mysql:8.0.18
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - d:/payrolldb1:/var/lib/mysql
      - ./dbscripts:/docker-entrypoint-initdb.d