-- MySQL Script generated by MySQL Workbench
-- 10/19/19 17:08:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ormlearn
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ormlearn
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ormlearn` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ormlearn` ;

-- -----------------------------------------------------
-- Table `ormlearn`.`department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ormlearn`.`department` ;

CREATE TABLE IF NOT EXISTS `ormlearn`.`department` (
  `dp_id` INT NOT NULL AUTO_INCREMENT,
  `dp_name` VARCHAR(45) NULL,
  PRIMARY KEY (`dp_id`),
  UNIQUE INDEX `name_UNIQUE` (`dp_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ormlearn`.`employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ormlearn`.`employee` ;

CREATE TABLE IF NOT EXISTS `ormlearn`.`employee` (
  `em_id` INT NOT NULL AUTO_INCREMENT,
  `em_name` VARCHAR(45) NULL,
  `em_salary` DOUBLE NULL,
  `em_permanent` TINYINT(1) NULL,
  `em_date_of_birth` DATE NULL,
  `em_dp_id` INT NULL,
  PRIMARY KEY (`em_id`),
  INDEX `em_dp_fk_idx` (`em_dp_id` ASC),
  CONSTRAINT `em_dp_fk`
    FOREIGN KEY (`em_dp_id`)
    REFERENCES `ormlearn`.`department` (`dp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ormlearn`.`skill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ormlearn`.`skill` ;

CREATE TABLE IF NOT EXISTS `ormlearn`.`skill` (
  `sk_id` INT NOT NULL AUTO_INCREMENT,
  `sk_name` VARCHAR(45) NULL,
  PRIMARY KEY (`sk_id`),
  UNIQUE INDEX `name_UNIQUE` (`sk_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ormlearn`.`employee_skill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ormlearn`.`employee_skill` ;

CREATE TABLE IF NOT EXISTS `ormlearn`.`employee_skill` (
  `es_id` INT NOT NULL AUTO_INCREMENT,
  `es_em_id` INT NOT NULL,
  `es_sk_id` INT NOT NULL,
  PRIMARY KEY (`es_id`),
  INDEX `es_sk_fk_idx` (`es_sk_id` ASC),
  CONSTRAINT `es_em_fk`
    FOREIGN KEY (`es_em_id`)
    REFERENCES `ormlearn`.`employee` (`em_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `es_sk_fk`
    FOREIGN KEY (`es_sk_id`)
    REFERENCES `ormlearn`.`skill` (`sk_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



CREATE TABLE IF NOT EXISTS `ormlearn`.`user` (
  `us_id` INT NOT NULL AUTO_INCREMENT,
  `us_name` VARCHAR(60) NOT NULL,
  `us_first_name` VARCHAR(100) NOT NULL,
  `us_last_name` VARCHAR(100) NULL,
  `us_password` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`us_id`),
  UNIQUE INDEX `us_name_UNIQUE` (`us_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ormlearn`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ormlearn`.`cart` (
  `ct_id` INT NOT NULL AUTO_INCREMENT,
  `ct_us_id` INT NOT NULL,
  `ct_total` INT NULL,
  PRIMARY KEY (`ct_id`),
  INDEX `fk_cart_user1_idx` (`ct_us_id` ASC),
  CONSTRAINT `ct_us_fk`
    FOREIGN KEY (`ct_us_id`)
    REFERENCES `ormlearn`.`user` (`us_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ormlearn`.`menu_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ormlearn`.`menu_item` (
  `me_id` INT NOT NULL AUTO_INCREMENT,
  `me_name` VARCHAR(100) NOT NULL,
  `me_price` DOUBLE NULL,
  `me_active` BIT(1) NOT NULL,
  `me_date_of_launch` DATE NULL,
  `me_category` VARCHAR(45) NULL,
  `me_free_delivery` BIT(1) NULL,
  `me_image_path` VARCHAR(500) NULL,
  PRIMARY KEY (`me_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ormlearn`.`cart_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ormlearn`.`cart_item` (
  `ci_id` INT NOT NULL AUTO_INCREMENT,
  `ci_me_id` INT NULL,
  `ci_quantity` INT NULL,
  `ci_ct_id` INT NULL,
  PRIMARY KEY (`ci_id`),
  INDEX `ci_ct_fk_idx` (`ci_ct_id` ASC),
  INDEX `ci_me_fk_idx` (`ci_me_id` ASC),
  CONSTRAINT `ci_ct_fk`
    FOREIGN KEY (`ci_ct_id`)
    REFERENCES `ormlearn`.`cart` (`ct_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ci_me_fk`
    FOREIGN KEY (`ci_me_id`)
    REFERENCES `ormlearn`.`menu_item` (`me_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ormlearn`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ormlearn`.`role` (
  `ro_id` INT NOT NULL AUTO_INCREMENT,
  `ro_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ro_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ormlearn`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ormlearn`.`user_role` (
  `ur_id` INT NOT NULL AUTO_INCREMENT,
  `ur_us_id` INT NOT NULL,
  `ur_ro_id` INT NULL,
  INDEX `fk_user_has_role_role1_idx` (`ur_ro_id` ASC),
  INDEX `fk_user_has_role_user1_idx` (`ur_us_id` ASC),
  PRIMARY KEY (`ur_id`),
  CONSTRAINT `ur_us_fk`
    FOREIGN KEY (`ur_us_id`)
    REFERENCES `ormlearn`.`user` (`us_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ur_ro_fk`
    FOREIGN KEY (`ur_ro_id`)
    REFERENCES `ormlearn`.`role` (`ro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `ormlearn`.`department`
-- -----------------------------------------------------
START TRANSACTION;
USE `ormlearn`;
INSERT INTO `ormlearn`.`department` (`dp_id`, `dp_name`) VALUES (DEFAULT, 'Payroll');
INSERT INTO `ormlearn`.`department` (`dp_id`, `dp_name`) VALUES (DEFAULT, 'Finance');
INSERT INTO `ormlearn`.`department` (`dp_id`, `dp_name`) VALUES (DEFAULT, 'Marketing');
INSERT INTO `ormlearn`.`department` (`dp_id`, `dp_name`) VALUES (DEFAULT, 'Manufacturing');

COMMIT;


-- -----------------------------------------------------
-- Data for table `ormlearn`.`employee`
-- -----------------------------------------------------
START TRANSACTION;
USE `ormlearn`;
INSERT INTO `ormlearn`.`employee` (`em_id`, `em_name`, `em_salary`, `em_permanent`, `em_date_of_birth`, `em_dp_id`) VALUES (DEFAULT, 'John', 10000, TRUE, '1999-01-01', 1);
INSERT INTO `ormlearn`.`employee` (`em_id`, `em_name`, `em_salary`, `em_permanent`, `em_date_of_birth`, `em_dp_id`) VALUES (DEFAULT, 'Jack', 12000, FALSE, '1998-01-01', 2);
INSERT INTO `ormlearn`.`employee` (`em_id`, `em_name`, `em_salary`, `em_permanent`, `em_date_of_birth`, `em_dp_id`) VALUES (DEFAULT, 'Paul', 8000, TRUE, '1997-01-01', 3);
INSERT INTO `ormlearn`.`employee` (`em_id`, `em_name`, `em_salary`, `em_permanent`, `em_date_of_birth`, `em_dp_id`) VALUES (DEFAULT, 'Emily', 11000, TRUE, '1999-02-01', 3);

COMMIT;


-- -----------------------------------------------------
-- Data for table `ormlearn`.`skill`
-- -----------------------------------------------------
START TRANSACTION;
USE `ormlearn`;
INSERT INTO `ormlearn`.`skill` (`sk_id`, `sk_name`) VALUES (DEFAULT, 'Excel');
INSERT INTO `ormlearn`.`skill` (`sk_id`, `sk_name`) VALUES (DEFAULT, 'Word');
INSERT INTO `ormlearn`.`skill` (`sk_id`, `sk_name`) VALUES (DEFAULT, 'Tally');

COMMIT;


-- -----------------------------------------------------
-- Data for table `ormlearn`.`employee_skill`
-- -----------------------------------------------------
START TRANSACTION;
USE `ormlearn`;
INSERT INTO `ormlearn`.`employee_skill` (`es_id`, `es_em_id`, `es_sk_id`) VALUES (DEFAULT, 1, 1);
INSERT INTO `ormlearn`.`employee_skill` (`es_id`, `es_em_id`, `es_sk_id`) VALUES (DEFAULT, 1, 2);
INSERT INTO `ormlearn`.`employee_skill` (`es_id`, `es_em_id`, `es_sk_id`) VALUES (DEFAULT, 2, 1);
INSERT INTO `ormlearn`.`employee_skill` (`es_id`, `es_em_id`, `es_sk_id`) VALUES (DEFAULT, 2, 3);
INSERT INTO `ormlearn`.`employee_skill` (`es_id`, `es_em_id`, `es_sk_id`) VALUES (DEFAULT, 3, 1);

COMMIT;





INSERT INTO ormlearn.user VALUES(1,'Scott', 'Scott', 'aaa', '$2y$10$qCGsTS9.PthuV4.tJ/n/4etDZbkcti/KU6yrqJhgQqH1d1EqaZhoa');
INSERT INTO ormlearn.user VALUES(2,'Smith', 'Smith', 'bbb', '$2y$10$qCGsTS9.PthuV4.tJ/n/4etDZbkcti/KU6yrqJhgQqH1d1EqaZhoa');


INSERT INTO ormlearn.role VALUES(1,'ROLE_ADMIN');
INSERT INTO ormlearn.role VALUES(2,'ROLE_USER');


INSERT INTO ormlearn.user_role VALUES(1,1,1);
INSERT INTO ormlearn.user_role VALUES(2,2,2);

